# GitHub Action to check TypeScript, Prettier, and ESLint
name: Lint & Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: TypeScript compile check
        run: npx tsc --noEmit
      - name: Run Prettier
        run: npx prettier . --check
      - name: Run ESLint
        run: npx eslint .
