name: Publish Galleries to GitHub Pages

on:
  push:
    branches-ignore:
      - gh-pages # avoid deploy loop

jobs:
  publish:
    name: Build & deploy each gallery
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - public_url: gallery
            data_folder: data
            folder: gallery
          - public_url: gallery/nac
            data_folder: dataNAC
            folder: nac
          - public_url: gallery/nerc
            data_folder: dataNERC
            folder: nerc
          - public_url: gallery/lac
            data_folder: dataLAC
            folder: lac
          - public_url: gallery/ae
            data_folder: dataAE
            folder: ae
          - public_url: gallery/aw
            data_folder: dataAW
            folder: aw
          - public_url: gallery/ap
            data_folder: dataAP
            folder: ap
          - public_url: gallery/eu
            data_folder: dataEU
            folder: eu
          - public_url: gallery/acpc
            data_folder: dataACPC
            folder: acpc

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build ${{ matrix.folder }} dataset
        env:
          PUBLIC_URL: ${{ matrix.public_url }}
          VITE_DATA_FOLDER: ${{ matrix.data_folder }}
          MODE: staging
        run: ./build.sh

      - name: Add .nojekyll (serve as‑is)
        run: touch "${{ matrix.public_url }}/.nojekyll"

      - name: Compute dest_dir
        id: dest
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          DATA="${{ matrix.folder }}"

          if [ "$DATA" = "gallery" ]; then
            if [ "$BRANCH" = "main" ]; then
              DIR="."                # /  (root)
            else
              DIR="$BRANCH"          # /feature-x/
            fi
          else
            if [ "$BRANCH" = "main" ]; then
              DIR="$DATA"            # /nac
            else
              DIR="$BRANCH/$DATA"    # /feature-x/nac
            fi
          fi

          echo "dir=$DIR" >> "$GITHUB_OUTPUT"

      - name: Publish ${{ matrix.folder }} to gh‑pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ matrix.public_url }}
          destination_dir: ${{ steps.dest.outputs.dir }}
          keep_files: true
