name: Publish via ftp

on: workflow_dispatch

jobs:
  build:
    name: Create artifacts from master
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - public_url: gallery # wf
            data_folder: data
          - public_url: galleryNAC # nac
            data_folder: dataNAC
          - public_url: galleryNERC # nerc
            data_folder: dataNERC
          - public_url: galleryLAC # lac
            data_folder: dataLAC
          - public_url: galleryAE # ae
            data_folder: dataAE
          - public_url: galleryAW # aw
            data_folder: dataAW
          - public_url: galleryAP # ap
            data_folder: dataAP
          - public_url: galleryEU # eu
            data_folder: dataEU
          - public_url: galleryACPC # acpc
            data_folder: dataACPC

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build
        run: PUBLIC_URL=${{ matrix.public_url }} VITE_DATA_FOLDER=${{ matrix.data_folder }} ./build.sh
      - name: Upload to ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp.u.icpc.global
          port: 21
          protocol: ftps
          username: live@u.icpc.global
          password: ${{ secrets.ftp_password }}
          local-dir: ${{ matrix.public_url }}/
          server-dir: ${{ matrix.public_url }}/
